apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-06-28T05:50:53Z"
  generation: 1
  labels:
    app: details-app
  name: details-app
  namespace: default
  resourceVersion: "63131"
  uid: b51305f1-151a-4dff-90bd-bd739a754b61
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: details-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: details-app
    spec:
      containers:
      - image: details-app:latest
        imagePullPolicy: Always
        name: details-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
